Login 버튼 추가
Parrotalk/Parrotalk_FE pull request #35
Opened 2024-12-02 02:11 UTC by KimGyeongLock

## 📌 개요 
  - 구글, 카카오 로그인 버튼 추가
 ## 💻 작업사항 
  - http://localhost:8080/oauth2/authorization/kakao, /google 링크로 연결

 ## 💡Issue 번호 
  - #6

2024-12-02 02:27 UTC, Austin-Choi requested changes
axios를 사용해 로그인을 요청할때 요청에서 헤더나 쿠키를 쓰지 않더라도 명시해 주어야 응답에서 헤더와 쿠키에 접근할 수 있기 때문에 이걸 적용하면 액세스 토큰과 쿠키가 넘어오지 않는 문제에 도움이 될 것 같습니다.

2024-12-02 02:27 UTC, Austin-Choi commented on src/components/CallHomeScreen.jsx
> +      await fetch(`${import.meta.env.VITE_API_BASE_URL}/api/v1/user/info`, {
outdated 된 fetch API 보다는 axios나 React query를 추천합니다. axios로 통일하면 좋을 것 같습니다!

2024-12-04 08:18 UTC, KimGyeongLock commented on src/components/CallHomeScreen.jsx
> +      await fetch(`${import.meta.env.VITE_API_BASE_URL}/api/v1/user/info`, {
수정하였습니다!

2024-12-04 23:48 UTC, Austin-Choi requested changes

2024-12-04 23:48 UTC, Austin-Choi commented on src/components/CallHomeScreen.jsx
> +        await axios.post(
전체적으로 보니 axios를 이용해 호출을 할때마다 반복되는 부분이 많습니다.
인증이 필요한 화면에서는 전부 쿠키랑 액세스 토큰을 포함하는 요청을 보내게 될 거 같은데 제가 추가해놓은 인터셉터 파일 활용 및 수정해서 공통인 부분은 인터셉터로 호출하고 달라지는 부분만 호출시에 덧붙이는 방법으로 하면 코드의 재사용성이 높아질 것 같습니다.

2024-12-05 05:31 UTC, KimGyeongLock commented on src/components/CallHomeScreen.jsx
> +        await axios.post(
추후 작업해 올리겠음

2024-12-05 05:36 UTC, merged